export const GET_ALL_LIBRARIES = 'GET_ALL_LIBRARIES';
export const GET_ALL_LIBRARIES_FAILURE = 'GET_ALL_LIBRARIES_FAILURE';
export const GET_ALL_LIBRARIES_SUCCESS = 'GET_ALL_LIBRARIES_SUCCESS';

export const GET_TESTIMONIALS_LIST = 'GET_TESTIMONIALS_LIST';
export const CLEAR_TESTIMONIALS_LIST = 'CLEAR_TESTIMONIALS_LIST';
export const GET_TESTIMONIALS_LIST_SUCCESS = 'GET_TESTIMONIALS_LIST_SUCCESS';

export const ADD_NEW_TESTIMONIAL = 'ADD_NEW_TESTIMONIAL';

export const SELECTED_TESTIMONIALSID = 'SELECTED_TESTIMONIALSID';
export const REMOVE_SELECTED_DATA = 'REMOVE_SELECTED_DATA';
export const ADD_TO_APPLICATION = 'ADD_TO_APPLICATION';
export const GET_ENABLED_COUNT = 'GET_ENABLED_COUNT';
export const EDIT_PAGE_TITLE = 'EDIT_PAGE_TITLE';
