export const EVENT_NAME = {
	// PROCESS
	PROCESS_UNCAUGHT_EXCEPTION: 'PROCESS_UNCAUGHT_EXCEPTION',

	// DATABASE
	DB_COLLECTION_CERATION_FAILED: 'DB_COLLECTION_CERATION_FAILED',
	DB_CONNECTION_FAILED: 'DB_CONNECTION_FAILED',

	// MODEL
	MODEL_INDEX_CREATION_FAILED: 'MODEL_INDEX_CREATION_FAILED',

	// FEEDBACK
	FEEDBACK_UPDATE_TS_IN_USER_RECORD: 'FEEDBACK_UPDATE_TS_IN_USER_RECORD',

	// IMAGES
	IMAGE_UPLOAD_FAIL: 'IMAGE_UPLOAD_FAIL',
	IMAGE_FETCH_FAIL: 'IMAGE_FETCH_FAIL',

	// Blob File Upload
	BLOB_MEDIA_UPLOAD_FAIL: 'BLOB MEDIA UPLOAD FAIL',
	BLOB_MEDIA_FETCH_FAIL: 'BLOB_MEDIA_FETCH_FAIL',

	// USER DATA
	INSERT_USER_DATA: 'INSERT_USER_DATA',
	FETCH_USER_DATA: 'FETCH_USER_DATA',
	FETCH_USER_DATA_BY_ID: 'FETCH_USER_DATA_BY_ID',
	DELETE_USER_DATA_BY_ID: 'DELETE_USER_DATA_BY_ID',
	UPDATE_USER_DATA_BY_ID: 'UPDATE_USER_DATA_BY_ID',
	INSERT_LOG_DATA: 'INSERT LOG DATA',
};
