import { createMuiTheme } from '@material-ui/core/styles';

// Create a theme instance.
const theme = createMuiTheme({
	typography: {
		fontFamily: 'Bogle',
		common: {
			fontFamily: 'Bogle',
			fontSize: 14,
			fontWeight: 'normal',
			fontStretch: 'normal',
			fontStyle: 'normal',
			lineHeight: 'normal',
			letterSpacing: 'normal',
		},
		subtitle1: {
			fontFamily: 'Bogle',
			fontSize: '24px',
			fontWeight: 'bold',
			fontStyle: 'normal',
			fontStretch: 'normal',
			lineHeight: 'normal',
			letterSpacing: 'normal',
			color: '#041f41',
		},
		subtitle2: {
			fontFamily: 'Bogle',
			fontSize: '16px',
			fontWeight: 'bold',
			fontStyle: 'normal',
			fontStretch: 'normal',
			lineHeight: '1.25',
			letterSpacing: 'normal',
			color: '#041f41',
		},
		heading1: {
			fontFamily: 'Bogle',
			fontSize: '24px',
			fontWeight: 'bold',
			fontStyle: 'normal',
			fontStretch: 'normal',
			lineHeight: 'normal',
			letterSpacing: 'normal',
			color: '#041f41',
			margin: '5px',
		},
		h4: {
			fontFamily: 'Bogle',
			fontSize: '15px',
			fontStyle: 'normal',
			fontStretch: 'normal',
			lineHeight: 'normal',
			letterSpacing: 'normal',
			color: '#9497ac',
			margin: 1,
		},
		pages: {
			display: 'flex',
			height: '90vh',
			alignItems: 'center',
			justifyContent: 'center',
			fontSize: '1rem',
		},
	},
	palette: {
		primary: {
			main: '#041f41',
			dark: '#151e53',
			light: '#4b5692',
			contrastText: '#adb0cb',
		},
		secondary: {
			main: '#041f41',
			dark: '#0469ad',
			light: '#37abf9',
			contrastText: '#fff',
		},
	},
	overrides: {
		MuiOutlinedInput: {
			root: {
				position: 'relative',
				'& $notchedOutline': {
					border: 'solid 1.5px #efefef',
					boxShadow: '0 2px 10px 0 rgba(205, 209, 226, 0.3)',
					outlineColor: '#efefef',
				},
				'&:hover:not($disabled):not($focused):not($error) $notchedOutline': {
					border: 'solid 1.5px #041f41 !important',
					boxShadow: '0 2px 10px 0 #041f41',
					outlineColor: '#041f41',
					'@media (hover: none)': {
						borderColor: '#041f41',
					},
				},
				'&$focused $notchedOutline': {
					border: 'solid 1.5px #041f41 !important',
					boxShadow: '0 2px 10px 0 #041f41',
					outlineColor: '#041f41',
					borderColor: '#041f41',
				},
			},
		},
		MuiFormLabel: {
			root: {
				'&$focused': {
					color: '#4A90E2',
				},
			},
		},
		MuiInput: {
			underline: {
				'&:hover:not($disabled):before': {
					borderBottom: '1px solid rgba(0, 0, 0, 0.42)',
				},
			},
		},
		MuiTypography: {
			body1: {
				fontSize: 14,
				fontWeight: 'bold',
				fontFamily: 'Bogle',
			},
		},
		MuiButton: {
			outlinedPrimary: {
				backgroundColor: 'inherit',
				fontSize: 12,
				fontWeight: 'bold',
				fontStyle: 'normal',
				fontStretch: 'normal',
				lineHeight: 'normal',
				letterSpacing: 'normal',
				border: 'solid 1px #041f41',
				margin: '0px 5px',
				borderRadius: '100px',
				padding: '10px 15px',
				color: '#041f41',
				width: 80,
				'&:hover': {
					backgroundColor: 'rgba(25, 118, 210, 0.08)',
					borderColor: '#041f41',
				},
			},
			outlinedSecondary: {
				backgroundColor: 'inherit',
				fontSize: 12,
				fontWeight: 'bold',
				fontStyle: 'normal',
				fontStretch: 'normal',
				lineHeight: 'normal',
				letterSpacing: 'normal',
				border: 'solid 1px rgba(173, 176, 203, 0.61)',
				margin: '0px 5px',
				borderRadius: '100px',
				padding: '10px 15px',
				color: 'white',
				width: 160,
				'&:hover': {
					backgroundColor: 'rgba(173, 176, 203, 0.08)',
					borderColor: 'white',
				},
			},
			containedPrimary: {
				backgroundColor: '#041f41',
				color: 'white',
				fontSize: 12,
				fontWeight: 'bold',
				fontStyle: 'normal',
				fontStretch: 'normal',
				lineHeight: 'normal',
				letterSpacing: 'normal',
				margin: '0px 5px',
				borderRadius: '100px',
				padding: '10px 15px',
				width: 80,
				'&:hover': {
					backgroundColor: '#041f41',
					color: 'white',
				},
			},
		},
	},
	custom: {
		heading1: {
			fontFamily: 'Bogle',
			fontSize: '24px',
			fontWeight: 'bold',
			fontStyle: 'normal',
			fontStretch: 'normal',
			lineHeight: 'normal',
			letterSpacing: 'normal',
			color: '#041f41',
			margin: '1px',
		},
		heading2: {
			fontFamily: 'Bogle',
			fontSize: '16px',
			fontWeight: 'bold',
			fontStyle: 'normal',
			fontStretch: 'normal',
			lineHeight: '1.25',
			letterSpacing: 'normal',
			color: '#041f41',
			margin: '4px',
		},
		contentSmall: {
			fontFamily: 'Bogle',
			fontSize: '14px',
			fontWeight: 'normal',
			fontStyle: 'normal',
			fontStretch: 'normal',
			lineHeight: 'normal',
			letterSpacing: 'normal',
			color: '#9497ac',
			margin: '1px',
		},
		contentVerySmall: {
			fontFamily: 'Bogle',
			fontSize: '12px',
			fontWeight: 'normal',
			fontStyle: 'normal',
			fontStretch: 'normal',
			lineHeight: 'normal',
			letterSpacing: 'normal',
			color: '#9497ac',
			margin: '1px',
		},
		contentVerySmallBold: {
			fontFamily: 'Bogle',
			fontSize: '12px',
			fontWeight: 'bold',
			fontStyle: 'normal',
			fontStretch: 'normal',
			lineHeight: 'normal',
			letterSpacing: 'normal',
			color: '#9497ac',
			margin: '1px',
		},
		contentSmallBold: {
			fontFamily: 'Bogle',
			fontSize: '14px',
			fontWeight: 'bold',
			fontStyle: 'normal',
			fontStretch: 'normal',
			lineHeight: 'normal',
			letterSpacing: 'normal',
			color: '#9497ac',
		},
		noWrap: {
			overflow: 'hidden',
			whiteSpace: 'nowrap',
			textOverflow: 'ellipsis',
		},
		centerText: {
			textAlign: 'center',
		},
		contentBig: {
			fontFamily: 'Bogle',
			fontSize: '20px',
			fontWeight: 'bold',
			fontStyle: 'normal',
			fontStretch: 'normal',
			lineHeight: 'normal',
			letterSpacing: 'normal',
			color: '#041f41',
			margin: '1px',
		},
	},
});

export default theme;
